version: '3'
services:
  fdp:
    build: .
    command: fdp-run 0.0.0.0 80 --db http://db:8890/sparql --grlc http://grlc:8088
    ports:
      - "80:80"
    healthcheck:
        test: curl --silent --fail http://0.0.0.0 || exit 1
        interval: 5s
    depends_on:
      - db
      - grlc
  db:
    image: "tenforce/virtuoso"
    ports:
        - "8890:8890"
        - "1111:1111"
    environment:
        SPARQL_UPDATE: "true"
  grlc:
    image: "clariah/grlc"
    ports:
      - "8088:8088"
    environment:
      - GRLC_SERVER_NAME=0.0.0.0:8088
      - GRLC_SPARQL_ENDPOINT=http://db:8890/sparql
      - DEBUG=true
    volumes:
      - ./fdp/sparql:/home/grlc/queries
    depends_on:
      - db